import asyncio
import discord
import random

from discord.ext import commands

client = commands.Bot(command_prefix="!")

@client.event
async def on_ready():
    print("Bot is ready to use!")

@client.event
async def on_message(message):
    if message.author == client.user:
        return
    elif message.content.startswith("/gather"):
        await client.send_message(message.channel, random.choice([ " A **Heart-shaped Leaf** is blown towards you by the wind. Nice! *(1 point)*",
                                                                     " What's this? A **Four-leafed Clover** sticks out amongst the grass! *(1 point)*",
                                                                     " Your eyes search until they land upon **One Half of a Mollusc Shell**. Good job! *(2 points)*",
                                                                     " A small ivory shape stands out amongst the clumps of dirt. It's a **Squirrel Skull**! *(4 points)*",
                                                                     " A crunchy noise pricks your ears. You look to find a **Shed Snake Skin** under your paws. *(3 points)*",
                                                                     " Something glimmers in the corner of your eye. **Dragonfly Wings**! Nice find! *(5 points)*",
                                                                     " Some **Egret Feathers** brush by your paws. How lucky! *(3 points)*",
                                                                     " What the...? A **Perfectly Round Pebble** sits by your paws! *(2 points)*",
                                                                     " A **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                     " An interesting shape appears before you. A **Forgotten Clay Totem**! *(5 points)*",
                                                                     " Your paw brushes by a **Rabbit Ribcage**. Good thing you didn't step on it! *(4 points)*",
                                                                     " A fuzzy object lies on the ground before you. It's a **Shed Antler**! *(4 points)*",
                                                                     " A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                     " Huh? Looks like you found an **Intact Net**. Good job! *(1 point)*",
                                                                     " Some **Elodea Strands** wrap around your paws. What luck! *(1 point)*",
                                                                     " A pretty flower has caught your eye. A **Lily Flower**! *(2 points)*",
                                                                     " Hmm? Something fell down from a branch. An **Acorn**! *(2 points)*",
                                                                     " A flash of red appears in the distance. It's a **Wild Strawberry**! *(4 points)*",
                                                                     " A funny smell caught your nose. A **Green Onion** sits before you. Nice! *(4 points)*",
                                                                     " A pretty water flower twirls towards you. It appears to be a **White Lotus Flower**. *(3 points)*",
                                                                     "A **Heart-shaped Leaf** is blown towards you by the wind. Nice! *(1 point)*",
                                                                     "What's this? A **Four-leafed Clover** sticks out amongst the grass! *(1 point)*",
                                                                     "Your eyes search until they land upon **One Half of a Mollusc Shell**. Good job! *(2 points)*",
                                                                     "A small ivory shape stands out amongst the clumps of dirt. It's a **Squirrel Skull**! *(4 points)*",
                                                                     "A crunchy noise pricks your ears. You look to find a **Shed Snake Skin** under your paws. *(3 points)*",
                                                                     "Something glimmers in the corner of your eye. **Dragonfly Wings**! Nice find! *(5 points)*",
                                                                     "Some **Egret Feathers** brush by your paws. How lucky! *(3 points)*",
                                                                     "What the...? A **Perfectly Round Pebble** sits by your paws! *(2 points)*",
                                                                     "A **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                     "An interesting shape appears before you. A **Forgotten Clay Totem**! *(5 points)*",
                                                                     "Your paw brushes by a **Rabbit Ribcage**. Good thing you didn't step on it! *(4 points)*",
                                                                     "A fuzzy object lies on the ground before you. It's a **Shed Antler**! *(4 points)*",
                                                                     "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                     "Huh? Looks like you found an **Intact Net**. Good job! *(1 point)*",
                                                                     "Some **Elodea Strands** wrap around your paws. What luck! *(1 point)*",
                                                                     "A pretty flower has caught your eye. A **Lily Flower**! *(2 points)*",
                                                                     "A **Heart-shaped Leaf** is blown towards you by the wind. Nice! *(1 point)*",
                                                                     "What's this? A **Four-leafed Clover** sticks out amongst the grass! *(1 point)*",
                                                                     "Your eyes search until they land upon **One Half of a Mollusc Shell**. Good job! *(2 points)*",
                                                                     "A small ivory shape stands out amongst the clumps of dirt. It's a **Squirrel Skull**! *(4 points)*",
                                                                     "A crunchy noise pricks your ears. You look to find a **Shed Snake Skin** under your paws. *(3 points)*",
                                                                     "Something glimmers in the corner of your eye. **Dragonfly Wings**! Nice find! *(5 points)*",
                                                                     "Some **Egret Feathers** brush by your paws. How lucky! *(3 points)*",
                                                                     "What the...? A **Perfectly Round Pebble** sits by your paws! *(2 points)*",
                                                                     "A **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                     "An interesting shape appears before you. A **Forgotten Clay Totem**! *(5 points)*",
                                                                     "Your paw brushes by a **Rabbit Ribcage**. Good thing you didn't step on it! *(4 points)*",
                                                                     "A fuzzy object lies on the ground before you. It's a **Shed Antler**! *(4 points)*",
                                                                     "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                     "Huh? Looks like you found an **Intact Net**. Good job! *(1 point)*",
                                                                     "Some **Elodea Strands** wrap around your paws. What luck! *(1 point)*",
                                                                     "A pretty flower has caught your eye. A **Lily Flower**! *(2 points)*",
                                                                     "A **Heart-shaped Leaf** is blown towards you by the wind. Nice! *(1 point)*",
                                                                     "What's this? A **Four-leafed Clover** sticks out amongst the grass! *(1 point)*",
                                                                     "Your eyes search until they land upon **One Half of a Mollusc Shell**. Good job! *(2 points)*",
                                                                     "A small ivory shape stands out amongst the clumps of dirt. It's a **Squirrel Skull**! *(4 points)*",
                                                                     "A crunchy noise pricks your ears. You look to find a **Shed Snake Skin** under your paws. *(3 points)*",
                                                                     "Something glimmers in the corner of your eye. **Dragonfly Wings**! Nice find! *(5 points)*",
                                                                     "Some **Egret Feathers** brush by your paws. How lucky! *(3 points)*",
                                                                     "What the...? A **Perfectly Round Pebble** sits by your paws! *(2 points)*",
                                                                     "A **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                     "An interesting shape appears before you. A **Forgotten Clay Totem**! *(5 points)*",
                                                                     "Your paw brushes by a **Rabbit Ribcage**. Good thing you didn't step on it! *(4 points)*",
                                                                     "A fuzzy object lies on the ground before you. It's a **Shed Antler**! *(4 points)*",
                                                                     "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                     "Huh? Looks like you found an **Intact Net**. Good job! *(1 point)*",
                                                                     "Some **Elodea Strands** wrap around your paws. What luck! *(1 point)*",
                                                                     "A pretty flower has caught your eye. A **Lily Flower**! *(2 points)*",
                                                                     "A **Heart-shaped Leaf** is blown towards you by the wind. Nice! *(1 point)*",
                                                                     "What's this? A **Four-leafed Clover** sticks out amongst the grass! *(1 point)*",
                                                                     "Your eyes search until they land upon **One Half of a Mollusc Shell**. Good job! *(2 points)*",
                                                                     "A small ivory shape stands out amongst the clumps of dirt. It's a **Squirrel Skull**! *(4 points)*",
                                                                     "A crunchy noise pricks your ears. You look to find a **Shed Snake Skin** under your paws. *(3 points)*",
                                                                     "Something glimmers in the corner of your eye. **Dragonfly Wings**! Nice find! *(5 points)*",
                                                                     "Some **Egret Feathers** brush by your paws. How lucky! *(3 points)*",
                                                                     "What the...? A **Perfectly Round Pebble** sits by your paws! *(2 points)*",
                                                                     "A **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                     "An interesting shape appears before you. A **Forgotten Clay Totem**! *(5 points)*",
                                                                     "Your paw brushes by a **Rabbit Ribcage**. Good thing you didn't step on it! *(4 points)*",
                                                                     "A fuzzy object lies on the ground before you. It's a **Shed Antler**! *(4 points)*",
                                                                     "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                     "Huh? Looks like you found an **Intact Net**. Good job! *(1 point)*",
                                                                     "Some **Elodea Strands** wrap around your paws. What luck! *(1 point)*",
                                                                     "A pretty flower has caught your eye. A **Lily Flower**! *(2 points)*",
                                                                     "A **Heart-shaped Leaf** is blown towards you by the wind. Nice! *(1 point)*",
                                                                     "What's this? A **Four-leafed Clover** sticks out amongst the grass! *(1 point)*",
                                                                     "Your eyes search until they land upon **One Half of a Mollusc Shell**. Good job! *(2 points)*",
                                                                     "A small ivory shape stands out amongst the clumps of dirt. It's a **Squirrel Skull**! *(4 points)*",
                                                                     "A crunchy noise pricks your ears. You look to find a **Shed Snake Skin** under your paws. *(3 points)*",
                                                                     "Something glimmers in the corner of your eye. **Dragonfly Wings**! Nice find! *(5 points)*",
                                                                     "Some **Egret Feathers** brush by your paws. How lucky! *(3 points)*",
                                                                     "What the...? A **Perfectly Round Pebble** sits by your paws! *(2 points)*",
                                                                     "A **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                     "An interesting shape appears before you. A **Forgotten Clay Totem**! *(5 points)*",
                                                                     "Your paw brushes by a **Rabbit Ribcage**. Good thing you didn't step on it! *(4 points)*",
                                                                     "A fuzzy object lies on the ground before you. It's a **Shed Antler**! *(4 points)*",
                                                                     "A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                     "Huh? Looks like you found an **Intact Net**. Good job! *(1 point)*",
                                                                     "Some **Elodea Strands** wrap around your paws. What luck! *(1 point)*",
                                                                     "A pretty flower has caught your eye. A **Lily Flower**! *(2 points)*",
                                                                     "Hmm? Something fell down from a branch. An **Acorn**! *(2 points)*",
                                                                     "A flash of red appears in the distance. It's a **Wild Strawberry**! *(4 points)*",
                                                                     "A funny smell caught your nose. A **Green Onion** sits before you. Nice! *(4 points)*",
                                                                     "A pretty water flower twirls towards you. It appears to be a **White Lotus Flower**. *(3 points)*",
                                                                     "  A **Heart-shaped Leaf** is blown towards you by the wind. Nice! *(1 point)*",
                                                                     "  What's this? A **Four-leafed Clover** sticks out amongst the grass! *(1 point)*",
                                                                     "  Your eyes search until they land upon **One Half of a Mollusc Shell**. Good job! *(2 points)*",
                                                                     "  A small ivory shape stands out amongst the clumps of dirt. It's a **Squirrel Skull**! *(4 points)*",
                                                                     "  A crunchy noise pricks your ears. You look to find a **Shed Snake Skin** under your paws. *(3 points)*",
                                                                     "  Something glimmers in the corner of your eye. **Dragonfly Wings**! Nice find! *(5 points)*",
                                                                     "  Some **Egret Feathers** brush by your paws. How lucky! *(3 points)*",
                                                                     "  What the...? A **Perfectly Round Pebble** sits by your paws! *(2 points)*",
                                                                     "  A **Crystal Quartz Point** catches your attention. Nice! *(5 points)*",
                                                                     "  An interesting shape appears before you. A **Forgotten Clay Totem**! *(5 points)*",
                                                                     "  Your paw brushes by a **Rabbit Ribcage**. Good thing you didn't step on it! *(4 points)*",
                                                                     "  A fuzzy object lies on the ground before you. It's a **Shed Antler**! *(4 points)*",
                                                                     "  A fluffy clump tumbles towards you. It's a **Cluster of Feathers**! *(1 point)*",
                                                                     "  Huh? Looks like you found an **Intact Net**. Good job! *(1 point)*",
                                                                     "  Some **Elodea Strands** wrap around your paws. What luck! *(1 point)*",
                                                                     "  A pretty flower has caught your eye. A **Lily Flower**! *(2 points)*",
                                                                     "  Hmm? Something fell down from a branch. An **Acorn**! *(2 points)*",
                                                                     "  A flash of red appears in the distance. It's a **Wild Strawberry**! *(4 points)*",
                                                                     "  A funny smell caught your nose. A **Green Onion** sits before you. Nice! *(4 points)*",
                                                                     "  A pretty water flower twirls towards you. It appears to be a **White Lotus Flower**. *(3 points)*",
                                                                     " Shiny! A **Shiny Fish Scale** flashes against the sun. *(6 points)*",
                                                                     " A large white object sits between some tree roots. A **Coyote Skull**! *(8 points)*",
                                                                     " Your paws carry you towards a **Glossy Turtle Shell**. Nice find! *(9 points)*",
                                                                     " Look at that! You found a **Veiled Bride Mushroom** in the grass. *(7 points)*",
                                                                     " A long, ivory object brushes by your paws. It looks to be a **Deer Femur**. *(10 points)*",
                                                                     " An interesting pattern caught your eye. It looks to be an **Opalized Snail Shell**. *(7 points)*",
                                                                     " Oh, what's this? Some **Glowing Lichen** stands out in the distance. *(6 points)*",
                                                                     " A sweet smell wafted into the air. You follow it to find a **Honeycomb Cluster**! *(10 points)*",
                                                                     " Your paws carry you towards a **Delicate Orchid**. Beautiful... *(9 points)*",
                                                                     " A hint of pink stands out on the water. A **Pink Lotus Flower**! *(7 points)*",
                                                                     " A flash of purple stands out on the water. A **Purple Lotus Flower**! *(8 points)*",
                                                                     "Shiny! A **Shiny Fish Scale** flashes against the sun. *(6 points)*",
                                                                     "A large white object sits between some tree roots. A **Coyote Skull**! *(8 points)*",
                                                                     "Your paws carry you towards a **Glossy Turtle Shell**. Nice find! *(9 points)*",
                                                                     "Look at that! You found a **Veiled Bride Mushroom** in the grass. *(7 points)*",
                                                                     "A long, ivory object brushes by your paws. It looks to be a **Deer Femur**. *(10 points)*",
                                                                     "An interesting pattern caught your eye. It looks to be an **Opalized Snail Shell**. *(7 points)*",
                                                                     "Oh, what's this? Some **Glowing Lichen** stands out in the distance. *(6 points)*",
                                                                     "A sweet smell wafted into the air. You follow it to find a **Honeycomb Cluster**! *(10 points)*",
                                                                     "Your paws carry you towards a **Delicate Orchid**. Beautiful... *(9 points)*",
                                                                     "A hint of pink stands out on the water. A **Pink Lotus Flower**! *(7 points)*",
                                                                     "A flash of purple stands out on the water. A **Purple Lotus Flower**! *(8 points)*",
                                                                     "Shiny! A **Shiny Fish Scale** flashes against the sun. *(6 points)*",
                                                                     "A large white object sits between some tree roots. A **Coyote Skull**! *(8 points)*",
                                                                     "Your paws carry you towards a **Glossy Turtle Shell**. Nice find! *(9 points)*",
                                                                     "Look at that! You found a **Veiled Bride Mushroom** in the grass. *(7 points)*",
                                                                     "A long, ivory object brushes by your paws. It looks to be a **Deer Femur**. *(10 points)*",
                                                                     "An interesting pattern caught your eye. It looks to be an **Opalized Snail Shell**. *(7 points)*",
                                                                     "Oh, what's this? Some **Glowing Lichen** stands out in the distance. *(6 points)*",
                                                                     "A sweet smell wafted into the air. You follow it to find a **Honeycomb Cluster**! *(10 points)*",
                                                                     "Your paws carry you towards a **Delicate Orchid**. Beautiful... *(9 points)*",
                                                                     "A hint of pink stands out on the water. A **Pink Lotus Flower**! *(7 points)*",
                                                                     "A flash of purple stands out on the water. A **Purple Lotus Flower**! *(8 points)*",
                                                                     " Something green sits amongst the wild flowers beside you. A **Jade Figurine**! *(12 points)*",
                                                                     " Oops! You stepped on a small object. It looks like a **Forgotten Brooch**. *(11 points)*",
                                                                     " Thank Caiga! You find a **Chunk of Nephrite** hiding between some rocks. *(14 points)*",
                                                                     " Bless Caiga! You find a **Chunk of Labradorite** hiding between some rocks. *(15 points)*",
                                                                     " How lucky! An **Ethereal Blue Lotus Flower** drifts along the water currents towards you. *(13 points)*",
                                                                     " A hint of pink stands out on the water. A **Pink Lotus Flower**! *(7 points)*",
                                                                     " A flash of purple stands out on the water. A **Purple Lotus Flower**! *(8 points)*",
                                                                     "Something green sits amongst the wild flowers beside you. A **Jade Figurine**! *(12 points)*",
                                                                     "Oops! You stepped on a small object. It looks like a **Forgotten Brooch**. *(11 points)*",
                                                                     "Thank Caiga! You find a **Chunk of Nephrite** hiding between some rocks. *(14 points)*",
                                                                     "Bless Caiga! You find a **Chunk of Labradorite** hiding between some rocks. *(15 points)*",
                                                                     "How lucky! An **Ethereal Blue Lotus Flower** drifts along the water currents towards you. *(13 points)*",
                                                                     "Your eyes catch on something glinting on the underside of a leaf... It's so small... What could it be...? Oh my! What a rare find! You obtain a **Shimmering Imperial Tortoise Beetle**! *(50 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     " A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     " Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     " Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     " Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "  A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "  Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "  Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "  Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "   A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "   Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "   Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "   Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "  A slimey creature sits on a large log. It's a **Gliding Snail**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "  Gotcha! A **Skittering Crustacean** is caught between your paws. It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "  Some movement flashes in the corner of your eye. You act quickly and catch a **Wriggling Newt**! It's not worth anything, but someone may want it...? *(0 points)*",
                                                                     "  Some croaking catches your attention. A **Skittish Frog** leaps away but is no match for your speed! It's not worth anything, but someone may want it...? *(0 points)*",]))

client.run("NTQzMjEyMzYyNjQ0MTkzMjgw.Dz64og.65FLw2MX4VHvsfJKioCmnaBUAQQ")
client.login(process.env.BOT_TOKEN);
